# CollectionBuilder 
# Jekyll Digital Collection Generator

# URL variables
# site domain 
url: https://www.lib.uidaho.edu
# location on the domain
# e.g. /digital/hjccc
baseurl: /demo/phs
# CONTENTdm server url
cdm-url: https://digital.lib.uidaho.edu
# location of code
source-code: https://github.com/CollectionBuilder

# Site settings
title: Potlatch Historical Society Collection
# header and head metadata
tagline: Depicting life in and around Potlatch, Idaho from 1880 to 1998
description: "Potlatch Historical Society Collection documents and images depicting life in and around Potlatch, Idaho from 1880 to 1998" 
# Organization branding
organization-name: "Digital Initiatives, University of Idaho Library"
organization-link: https://www.lib.uidaho.edu/digital/
organization-logo-banner: https://www.lib.uidaho.edu/media/digital/justdi_logo_sm.png
organization-logo-nav: https://www.lib.uidaho.edu/media/digital/bannerlogo_allwhite.png

# Collection settings
# contentdm collection name 
cdm-collection-id: phs
# name of metadata file, be sure to also change page_gen data setting!
metadata: phs 
# page gen settings 
# "data" value must be the name of the metadata file
page_gen:
  - data: 'phs'
    template: 'items'
    name: 'objectid'
    dir: 'items'
    extension: 'html'   

# Note: use environment variable on build command to include analytics
# JEKYLL_ENV=production jekyll build
# if present, used to add analytics during build
google-analytics-id: 

# add liquid profiler to id bottlenecks
# profile: true

exclude: [docs/, Rakefile, README.md, LICENSE]

# compress CSS output
sass:
  style: compressed
