# CollectionBuilder 
# Jekyll Digital Collection Generator

# URL variables
# site domain 
url: https://www.lib.uidaho.edu
# location on the domain
# e.g. /digital/hjccc
baseurl: /digital/vandalvideo
# CONTENTdm server url
cdm-url: https://digital.lib.uidaho.edu
# location of code
source-code: https://github.com/CollectionBuilder

# Site settings
title: Vandal Video Collection
# header and head metadata
tagline: Historic videos of University of Idaho Basketball and Football Games, 1925 - 1997
description: "The Vandal Video Collection is a collection of 160+ digitized 16mm Film reels that were scouting videos for both football and basketball games.." 
# Organization branding
organization-name: "Digital Initiatives, University of Idaho Library"
organization-link: https://www.lib.uidaho.edu/digital/
organization-logo-banner: https://www.lib.uidaho.edu/media/digital/justdi_logo_sm.png
organization-logo-nav: https://www.lib.uidaho.edu/media/digital/bannerlogo_allwhite.png

# Collection settings
# contentdm collection name 
cdm-collection-id: vandalvideo
# name of metadata file, be sure to also change page_gen data setting!
metadata: vandalvideo 
# page gen settings 
# "data" value must be the name of the metadata file
page_gen:
  - data: 'vandalvideo'
    template: 'items'
    name: 'objectid'
    dir: 'items'
    extension: 'html'   

# Note: use environment variable on build command to include analytics
# JEKYLL_ENV=production jekyll build
# if present, used to add analytics during build
google-analytics-id: 

# add liquid profiler to id bottlenecks
# profile: true

exclude: [docs/, Rakefile, README.md, LICENSE]

# compress CSS output
sass:
  style: compressed
